services:
  https-server31:
    environment:
      - BASE_IP=4.4.31.1
    image: 192.168.83.9:30443/test/ubuntu_base
    stdin_open: true
    tty: true
    restart: always
    privileged: true
    container_name: https-server31
    volumes:
      - ./tls_test_server:/home/tls_test_server
    entrypoint: /home/tls_test_server/tls_test_server -k /home/tls_test_server/server.key -c /home/tls_test_server/server.crt
    networks:
      wnet:
        ipv4_address: 4.4.31.1
    cap_add:
      - NET_ADMIN
networks:
  wnet:
    external:
      name: wnet

