services:
  ftps-server26:
    environment:
      - BASE_IP=4.4.26.1
      - INTERFACE_NAME=eth0
      - FTP_SERVER_PORT=21
      - IP=4.4.26.1
    networks:
      wnet:
        ipv4_address: 4.4.26.1
    #entrypoint: /entrypoint.sh
    image: 192.168.83.9:30443/test/ftpd-server
    stdin_open: true
    tty: true
    restart: always
    privileged: true
    container_name: ftps-server26
networks:
  wnet:
    external:
      name: wnet

