services:
  ftp-client30:
    environment:
      - BASE_IP=3.3.30.1
      - IP_COUNT=1
      - IP_CIDR=16
      - INTERFACE_NAME=eth0
      - ROUTE_DST=default
      - FTP_SERVER_PORT=21
      - FTP_SERVER_IP=4.4.30.1
    image: 192.168.83.9:30443/test/ftp-client
    command: sh -c "/entrypoint.sh"
    stdin_open: true
    tty: true
    restart: always
    privileged: true
    container_name: ftp-client30
    networks:
      wnet:
        ipv4_address: 3.3.30.1
networks:
  wnet:
    external:
      name: wnet

