services:
  http-server7:
    environment:
      - BASE_IP=4.4.7.1
    image: 192.168.83.9:30443/test/http-server
    stdin_open: true
    tty: true
    restart: always
    privileged: true
    container_name: http-server7
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      wnet:
        ipv4_address: 4.4.7.1
    cap_add:
      - NET_ADMIN
    ports:
      - "8080:8080"
networks:
  wnet:
    external:
      name: wnet

